CREATE TABLE `carQuoteSubmissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`locale` varchar(8) NOT NULL,
	`fullName` varchar(160) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(40) NOT NULL,
	`city` varchar(120),
	`postalCode` varchar(12) NOT NULL,
	`validatedAddress` text,
	`driverAge` int NOT NULL,
	`accidentCount` int NOT NULL DEFAULT 0,
	`ticketCount` int NOT NULL DEFAULT 0,
	`priorInsurance` varchar(24) NOT NULL,
	`historyNotes` text,
	`vehicleYear` int NOT NULL,
	`vehicleMake` varchar(120) NOT NULL,
	`vehicleModel` varchar(160) NOT NULL,
	`estimatedAnnualPremium` int NOT NULL,
	`estimatedMonthlyPremium` int NOT NULL,
	`manualReview` int NOT NULL DEFAULT 0,
	`source` varchar(80) NOT NULL DEFAULT 'website',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `carQuoteSubmissions_id` PRIMARY KEY(`id`)
);
